# Generated by Django 6.0.4 on 2026-04-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='nationality',
            field=models.CharField(default='Bangladeshi', max_length=100),
        ),
    ]
