# Generated by Django 6.0.4 on 2026-04-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userdata_age_userdata_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('section', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
            ],
        ),
    ]
