# Generated by Django 6.0.4 on 2026-04-23 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='country',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
    ]
