# Generated by Django 6.0.4 on 2026-04-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_students_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='c_name',
            new_name='country_name',
        ),
    ]
